version: '3'
services:
  tweet_collector:
    build: tweet_collector/
    volumes:
    - ./tweet_collector/:/code
    links:
    - mongodb
  mongodb:
    image: mongo
    ports:
    - 27017:27017
  etl_job:
    build: etl_job/
    volumes:
    - ./etl_job/:/code
    links:
      - mongodb
